version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379
  memcached:
    image: memcached:1.5.12-alpine
    ports:
      - 11211:11211
